
// Carriers
//

#define CARRIERCOUNT     57

static const WCHAR Carriers[CARRIERCOUNT][30] = {
	L"Aegean Airlines",
	L"Aeroflot",
	L"Aerolíneas Argentinas",
	L"Aeroméxico",
	L"Air Canada",
	L"Air China",
	L"Air Europa",
	L"Air France",
	L"Air India",
	L"Air New Zealand",
	L"Alitalia",
	L"American Airlines",
	L"ANA",
	L"Asiana Airlines",
	L"Austrian Airlines",
	L"Avianca",
	L"British Airways",
	L"Brussels Airlines",
	L"Cathay Pacific",
	L"China Airlines",
	L"China Eastern Airlines",
	L"Czech Airlines",
	L"Copa Airlines",
	L"Croatia Airlines",
	L"Delta Air Lines",
	L"EgyptAir",
	L"Ethiopian Airlines",
	L"EVA Air",
	L"Finnair",
	L"Garuda Indonesia",
	L"Iberia",
	L"Japan Airlines",
	L"Kenya Airways",
	L"KLM",
	L"Korean Air",
	L"LOT Polish Airlines",
	L"Lufthansa",
	L"Malaysia Airlines",
	L"Middle East Airlines",
	L"Quantas",
	L"Qatar Airways",
	L"Royal Air Maroc",
	L"Royal Jordanian",
	L"S7 Airlines",
	L"Saudia",
	L"Scandinavian Airlines (SAS)",
	L"Shenzhen Airlines",
	L"Singapore Airlines",
	L"SriLankan Airlines",
	L"Swiss",
	L"TAP Portugal",
	L"TAROM",
	L"Thai Airways",
	L"Turkish Airlines",
	L"United Airlines",
	L"Vietnam Airlines",
	L"XiamenAir"
};


// Equipment
//

#define EQUIPMENTCOUNT     31

static const WCHAR Equipment[EQUIPMENTCOUNT][21] = {
	L"Airbus A220",
	L"Airbus A300",
	L"Airbus A310",
	L"Airbus A318",
	L"Airbus A319",
	L"Airbus A320",
	L"Airbus A321",
	L"Airbus A330",
	L"Airbus A340",
	L"Airbus A350",
	L"Airbus A380",
	L"Avro Regional Jet",
	L"Boeing 707",
	L"Boeing 717",
	L"Boeing 727",
	L"Boeing 737",
	L"Boeing 747",
	L"Boeing 757",
	L"Boeing 767",
	L"Boeing 777",
	L"Boeing 787",
	L"Canadair CRJ-200",
	L"Canadair CRJ-300",
	L"Canadair CRJ-900",
	L"Embraer ERJ-145",
	L"Embraer ERJ-175",
	L"Embraer ERJ-195",
	L"Fokker 50/60",
	L"Fokker 70/100",
	L"MD-11",
	L"Sukhoi Super Jet 100"
};
