//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Flightmap.rc
//
#define IDR_APPLICATION                 128
#define IDB_GLOBEICONS_RGB              130
#define IDB_GLOBEICONS_ALPHA            131
#define IDB_BLUEMARBLE_1024             132
#define IDB_BLUEMARBLE_2048             133
#define IDB_BLUEMARBLE_4096             134
#define IDB_BLUEMARBLE_8192             135
#define IDB_NIGHT_8192                  136
#define IDB_GRAY_8192                   137
#define IDB_DOCKED                      138
#define IDB_SANTA                       139
#define IDB_BACKGROUNDS                 140
#define IDB_MENUBARICONS                141
#define IDB_MENUFILE_16                 142
#define IDB_MENUFILE_32                 143
#define IDB_MENUEDIT_16                 144
#define IDB_MENUEDIT_32                 145
#define IDB_MENUMAP_16                  146
#define IDB_MENUMAP_32                  147
#define IDB_MENUGLOBE_16                148
#define IDB_MENUGLOBE_32                149
#define IDB_MENUGOOGLEEARTH_16          150
#define IDB_MENUGOOGLEEARTH_32          151
#define IDB_MENUMAPWND_16               152
#define IDB_MENUMAPWND_32               153
#define IDB_MENUMAPVIEW_16              154
#define IDB_MENUMAPVIEW_32              155
#define IDB_MENUGLOBEWND_16             156
#define IDB_MENUGLOBEWND_32             157
#define IDB_MENUGLOBEVIEW_16            158
#define IDB_MENUGLOBEVIEW_32            159
#define IDB_MENUGLOBEITEM_16            160
#define IDB_MENUGLOBEITEM_32            161
#define IDB_MENUDETAILS_16              162
#define IDB_MENUDETAILS_32              163
#define IDB_FLAGS_16                    164
#define IDB_FLAGS_16i                   165
#define IDB_FLAGS_32                    166
#define IDS_RECENTFILES                 1000
#define IDS_SAMPLEITINERARIES           1001
#define IDS_SAVECOPY                    1002
#define IDS_EXPORT                      1003
#define IDS_PRINTPREVIEW                1004
#define IDS_PREPAREDISTRIBUTION         1005
#define IDS_BACKGROUND                  1006
#define IDS_FLIGHTROUTES                1007
#define IDS_LOCATIONS                   1008
#define IDS_IATACODES                   1009
#define IDS_YOULOOKAT                   1010
#define IDS_DRIVENOTREADY               1011
#define IDS_FLIGHTCOUNT_SINGULAR        1012
#define IDS_FLIGHTCOUNT_PLURAL          1013
#define IDS_BACKGROUND_DEFAULT          1014
#define IDS_BACKGROUND_NIGHT            1015
#define IDS_BACKGROUND_ABSTRACT         1016
#define IDS_BACKGROUND_COLOR            1017
#define IDS_EMPTYITINERARY              1018
#define IDS_SAMPLEITINERARY             1019
#define IDS_NOTSAVED                    1020
#define IDS_ATTACHMENTS                 1021
#define IDS_AWARDFLIGHT                 1022
#define IDS_BUSINESSTRIP                1023
#define IDS_LEISURETRIP                 1024
#define IDS_EDITFLIGHT                  1025
#define IDS_FILEFILTER_AIR              1100
#define IDS_FILEFILTER_AIRX             1101
#define IDS_FILEFILTER_BMP              1102
#define IDS_FILEFILTER_CSV              1103
#define IDS_FILEFILTER_ICS              1104
#define IDS_FILEFILTER_JPEG             1105
#define IDS_FILEFILTER_KML              1106
#define IDS_FILEFILTER_PNG              1107
#define IDS_FILEFILTER_TIFF             1108
#define IDS_FILEFILTER_TXT              1109
#define IDS_COLUMN0                     1200
#define IDS_COLUMN1                     1201
#define IDS_COLUMN2                     1202
#define IDS_COLUMN3                     1203
#define IDS_COLUMN4                     1204
#define IDS_COLUMN5                     1205
#define IDS_COLUMN6                     1206
#define IDS_COLUMN7                     1207
#define IDS_COLUMN8                     1208
#define IDS_COLUMN9                     1209
#define IDS_COLUMN10                    1210
#define IDS_COLUMN11                    1211
#define IDS_COLUMN12                    1212
#define IDS_COLUMN13                    1213
#define IDS_COLUMN14                    1214
#define IDS_COLUMN15                    1215
#define IDS_COLUMN16                    1216
#define IDS_COLUMN17                    1217
#define IDS_COLUMN18                    1218
#define IDS_COLUMN19                    1219
#define IDS_COLUMN20                    1220
#define IDS_COLUMN21                    1221
#define IDS_COLUMN22                    1222
#define IDS_COLUMN23                    1223
#define IDS_METADATA_COMMENTS           1300
#define IDS_METADATA_TITLE_ATLANTIC     1301
#define IDS_METADATA_TITLE_PACIFIC      1302
#define IDS_METADATA_KEYWORDS_ATLANTIC  1303
#define IDS_METADATA_KEYWORDS_PACIFIC   1304
#define IDD_ROUTE                       2000
#define IDC_FROM_IATA                   2001
#define IDC_FROM_SELECT                 2002
#define IDC_FROM_TIME                   2003
#define IDC_FROM_GATE                   2004
#define IDC_TO_IATA                     2005
#define IDC_TO_SELECT                   2006
#define IDC_TO_TIME                     2007
#define IDC_TO_GATE                     2008
#define IDC_WAYPOINT_BTN                2009
#define IDC_WAYPOINT_DISPLAY            2010
#define IDC_FLIGHTTIME                  2011
#define IDC_COMMENT                     2012
#define IDD_OTHER                       2100
#define IDC_AIRLINE                     2101
#define IDC_FLIGHTNO                    2102
#define IDC_CODESHARES                  2103
#define IDC_EQUIPMENT                   2104
#define IDC_REGISTRATION                2105
#define IDC_AIRCRAFTNAME                2106
#define IDC_CLASS_Y                     2107
#define IDC_CLASS_YP                    2108
#define IDC_CLASS_J                     2109
#define IDC_CLASS_F                     2110
#define IDC_CLASS_C                     2111
#define IDC_ETIXCODE                    2112
#define IDC_FARE                        2113
#define IDC_BUSINESSTRIP                2114
#define IDC_LEISURETRIP                 2115
#define IDC_AWARDMILES                  2116
#define IDC_STATUSMILES                 2117
#define IDC_AWARDFLIGHT                 2118
#define IDC_CHOOSECOLOR                 2119
#define IDC_RATING                      2120
#define IDC_SEAT                        2121
#define IDD_ATTACHMENTS                 2200
#define IDM_FILE                        3000
#define IDM_FILE_NEW                    3001
#define IDM_FILE_NEWSAMPLE1             3002
#define IDM_FILE_NEWSAMPLE2             3003
#define IDM_FILE_OPEN                   3004
#define IDM_FILE_SAVE                   3005
#define IDM_FILE_SAVEAS                 3006
#define IDM_FILE_SAVEAS_AIRX            3007
#define IDM_FILE_SAVEAS_ICS             3008
#define IDM_FILE_SAVEAS_CSV             3009
#define IDM_FILE_SAVEAS_TXT             3010
#define IDM_FILE_SAVEAS_OTHER           3011
#define IDM_FILE_PRINT                  3012
#define IDM_FILE_PRINT_QUICK            3013
#define IDM_FILE_PRINT_PREVIEW          3014
#define IDM_FILE_PREPARE                3015
#define IDM_FILE_PREPARE_PROPERTIES     3016
#define IDM_FILE_PREPARE_INSPECT        3017
#define IDM_FILE_PREPARE_ATTACHMENTS    3018
#define IDM_FILE_CLOSE                  3019
#define IDM_FILE_QUIT                   3020
#define IDM_FILE_RECENT                 3050
#define IDM_EDIT                        3100
#define IDM_EDIT_CUT                    3101
#define IDM_EDIT_COPY                   3102
#define IDM_EDIT_PASTE                  3103
#define IDM_EDIT_INSERT_FLIGHT          3104
#define IDM_EDIT_INSERT_ROUTE           3105
#define IDM_EDIT_INSERT_ITINERARY       3106
#define IDM_EDIT_DELETE                 3107
#define IDM_EDIT_SELECTALL              3108
#define IDM_MAP                         3200
#define IDM_MAP_OPEN                    3201
#define IDM_MAP_EXPORT_BMP              3202
#define IDM_MAP_EXPORT_JPEG             3203
#define IDM_MAP_EXPORT_PNG              3204
#define IDM_MAP_EXPORT_TIFF             3205
#define IDM_MAP_MERGEMETRO              3206
#define IDM_MAP_BACKGROUND              3207
#define IDM_MAP_BACKGROUNDCOLOR         3208
#define IDM_MAP_RESOLUTION              3209
#define IDM_MAP_CENTERATLANTIC          3210
#define IDM_MAP_CENTERPACIFIC           3211
#define IDM_MAP_SHOWFLIGHTROUTES        3212
#define IDM_MAP_STRAIGHTLINES           3213
#define IDM_MAP_ARROWS                  3214
#define IDM_MAP_USECOUNT                3215
#define IDM_MAP_USECOLORS               3216
#define IDM_MAP_ROUTECOLOR              3217
#define IDM_MAP_SHOWLOCATIONS           3218
#define IDM_MAP_LOCATIONINNERCOLOR      3219
#define IDM_MAP_LOCATIONOUTERCOLOR      3220
#define IDM_MAP_SHOWIATACODES           3221
#define IDM_MAP_IATAINNERCOLOR          3222
#define IDM_MAP_IATAOUTERCOLOR          3223
#define IDM_GLOBE                       3300
#define IDM_GLOBE_OPEN                  3301
#define IDM_GLOBE_MERGEMETRO            3302
#define IDM_GOOGLEEARTH                 3400
#define IDM_GOOGLEEARTH_OPEN            3401
#define IDM_GOOGLEEARTH_EXPORT          3402
#define IDM_GOOGLEEARTH_MERGEMETRO      3403
#define IDM_GOOGLEEARTH_COLORS          3404
#define IDM_GOOGLEEARTH_CLAMP           3405
#define IDM_STATISTICS                  3500
#define IDM_MAPWND                      3600
#define IDM_MAPWND_COPY                 3601
#define IDM_MAPWND_SAVEAS               3602
#define IDM_MAPWND_PRINT                3603
#define IDM_MAPWND_PRINT_QUICK          3604
#define IDM_MAPWND_PRINT_PREVIEW        3605
#define IDM_MAPWND_CLOSE                3606
#define IDM_MAPVIEW                     3700
#define IDM_MAPVIEW_ZOOMIN              3701
#define IDM_MAPVIEW_ZOOMOUT             3702
#define IDM_MAPVIEW_AUTOSIZE            3703
#define IDM_GLOBEWND                    3800
#define IDM_GLOBEWND_CLOSE              3801
#define IDM_GLOBEVIEW                   3900
#define IDM_GLOBEVIEW_SAVEAS            3901
#define IDM_GLOBEVIEW_JUMPTOLOCATION    3902
#define IDM_GLOBEVIEW_ZOOMIN            3903
#define IDM_GLOBEVIEW_ZOOMOUT           3904
#define IDM_GLOBEVIEW_AUTOSIZE          3905
#define IDM_GLOBEVIEW_COLORS            3906
#define IDM_GLOBEVIEW_CLAMP             3907
#define IDM_GLOBEVIEW_SPOTS             3908
#define IDM_GLOBEVIEW_AIRPORTIATA       3909
#define IDM_GLOBEVIEW_AIRPORTNAMES      3910
#define IDM_GLOBEVIEW_GPS               3911
#define IDM_GLOBEVIEW_FLIGHTCOUNT       3912
#define IDM_GLOBEVIEW_VIEWPORT          3913
#define IDM_GLOBEVIEW_CROSSHAIRS        3914
#define IDM_GLOBEVIEW_3DSETTINGS        3915
#define IDM_GLOBEITEM                   4000
#define IDM_GLOBEITEM_OPENGOOGLEEARTH   4001
#define IDM_DETAILS                     4100
#define IDM_DETAILS_AUTOSIZEALL         4101
#define IDM_DETAILS_AUTOSIZE            4102
#define IDM_DETAILS_CHOOSE              4103

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        8011
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         8038
#define _APS_NEXT_SYMED_VALUE           8007
#endif
#endif
