//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Flightmap.rc
//
#define IDB_RESOLUTIONPRESETICONS_16    130
#define IDB_RESOLUTIONPRESETICONS_24    131
#define IDB_RESOLUTIONPRESETICONS_32    132
#define IDB_FILEMENU_16                 133
#define IDB_FILEMENU_24                 134
#define IDB_FILEMENU_32                 135
#define IDB_FILEMENU_48                 136
#define IDB_FILEMENU_64                 137
#define IDB_SIDEBAR_16                  138
#define IDB_SIDEBAR_24                  139
#define IDB_SIDEBAR_32                  140
#define IDB_SIDEBAR_48                  141
#define IDB_SIDEBAR_64                  142
#define IDB_TASKS_ATTACHMENTS_16        143
#define IDB_TASKS_ATTACHMENTS_24        144
#define IDB_TASKS_ATTACHMENTS_32        145
#define IDB_TASKS_ATTACHMENTS_48        146
#define IDB_TASKS_ATTACHMENTS_64        147
#define IDB_TASKS_ITINERARY_16          148
#define IDB_TASKS_ITINERARY_24          149
#define IDB_TASKS_ITINERARY_32          150
#define IDB_TASKS_ITINERARY_48          151
#define IDB_TASKS_ITINERARY_64          152
#define IDB_TASKS_MAP_16                153
#define IDB_TASKS_MAP_24                154
#define IDB_TASKS_MAP_32                155
#define IDB_TASKS_MAP_48                156
#define IDB_TASKS_MAP_64                157
#define IDB_TASKS_GLOBE_16              158
#define IDB_TASKS_GLOBE_24              159
#define IDB_TASKS_GLOBE_32              160
#define IDB_TASKS_GLOBE_48              161
#define IDB_TASKS_GLOBE_64              162
#define IDB_FLAGS_16                    163
#define IDB_FLAGS_24                    164
#define IDB_FLAGS_32                    165
#define IDB_FLAGS_48                    166
#define IDB_FLAGS_64                    167
#define IDB_METROPOLITAN_DISTINCT       168
#define IDB_METROPOLITAN_MERGED         169
#define IDB_SEATICONS                   170
#define IDB_BLUEMARBLE_512              171
#define IDB_NIGHT_512                   172
#define IDB_NIGHT_8192                  173
#define IDB_ABSTRACT_512                174
#define IDB_ABSTRACT_8192               175
#define IDS_DRIVENOTREADY               1000
#define IDS_ILLEGALFORMAT               1001
#define IDS_FLIGHTCOUNT_SINGULAR        1002
#define IDS_FLIGHTCOUNT_PLURAL          1003
#define IDS_BACKGROUND_DEFAULT          1004
#define IDS_BACKGROUND_NIGHT            1005
#define IDS_BACKGROUND_ABSTRACT         1006
#define IDS_BACKGROUND_COLOR            1007
#define IDS_EMPTYITINERARY              1008
#define IDS_FILTEREDITINERARY           1009
#define IDS_SAMPLEITINERARY             1010
#define IDS_NOTSAVED                    1011
#define IDS_ATTACHMENTS                 1012
#define IDS_AWARDFLIGHT                 1013
#define IDS_GROUNDTRANSPORTATION        1014
#define IDS_BUSINESSTRIP                1015
#define IDS_LEISURETRIP                 1016
#define IDS_UPGRADE                     1017
#define IDS_CANCELLED                   1018
#define IDS_EDITFLIGHT                  1019
#define IDS_CUEBANNER_DATETIME          1020
#define IDS_CUEBANNER_TIME              1021
#define IDS_CUEBANNER_ROUTE             1022
#define IDS_PRINTED_UNREGISTERED        1023
#define IDS_PRINTED_REGISTERED          1024
#define IDS_METADATA_COMMENTS           1025
#define IDS_METADATA_TITLE_ATLANTIC     1026
#define IDS_METADATA_TITLE_PACIFIC      1027
#define IDS_METADATA_KEYWORDS_ATLANTIC  1028
#define IDS_METADATA_KEYWORDS_PACIFIC   1029
#define IDS_SUBITEM_NAME                1030
#define IDS_SUBITEM_CREATED             1031
#define IDS_SUBITEM_MODIFIED            1032
#define IDS_SUBITEM_SIZE                1033
#define IDS_ATTACHMENT_TOOLARGE         1034
#define IDS_ATTACHMENT_TOOMANY          1035
#define IDS_FILESTATUS_SINGULAR         1036
#define IDS_FILESTATUS_PLURAL           1037
#define IDS_DELETE_CAPTION              1038
#define IDS_DELETE_FILE                 1039
#define IDS_DELETE_ALL                  1040
#define IDS_REVENUEFLIGHTS              1041
#define IDS_NONREVFLIGHTS               1042
#define IDS_INCLUDESCREW                1043
#define IDS_CLASS_F                     1044
#define IDS_CLASS_J                     1045
#define IDS_CLASS_YP                    1046
#define IDS_CLASS_Y                     1047
#define IDS_CLASS_CHARTER               1048
#define IDS_CLASS_CREW                  1049
#define IDS_MILES                       1050
#define IDS_FLIGHTS                     1051
#define IDS_ROUTE                       1052
#define IDS_FLIGHTS_SINGULAR            1053
#define IDS_FLIGHTS_PLURAL              1054
#define IDS_RESOLUTION                  1055
#define IDS_TOOLTIP_UINT                1056
#define IDS_TOOLTIP_TIME                1057
#define IDS_TOOLTIP_DISTANCE            1058
#define IDS_TOOLTIP_DATETIME            1059
#define IDS_FINDREPLACE                 1060
#define IDS_ILLEGALCOLUMN_FIND          1061
#define IDS_ILLEGALCOLUMN_REPLACE       1062
#define IDS_ALLREPLACED                 1063
#define IDS_SEARCHTERMNOTFOUND          1064
#define IDS_REPLACEQUESTION             1065
#define IDS_NORENDERINGCONTEXT          1066
#define IDS_QUALITY_LOW                 1067
#define IDS_QUALITY_MEDIUM              1068
#define IDS_QUALITY_HIGH                1069
#define IDS_QUALITY_ULTRA               1070
#define IDS_GOOGLEEARTH                 1071
#define IDS_STATISTICS                  1072
#define IDS_MAPSETTINGS                 1073
#define IDS_COLUMN_RESOLUTION           1074
#define IDS_COLUMN_APPLICATION          1075
#define IDS_FILEMENU_NEW                1100
#define IDS_FILEMENU_TEMPLATES          1101
#define IDS_FILEMENU_OPEN               1102
#define IDS_FILEMENU_SAVE               1103
#define IDS_FILEMENU_SAVEAS             1104
#define IDS_FILEMENU_CONVERT            1105
#define IDS_FILEMENU_OTHERFORMATS       1106
#define IDS_FILEMENU_PRINT              1107
#define IDS_FILEMENU_DEFAULTPRINTER     1108
#define IDS_FILEMENU_PREPARE            1109
#define IDS_FILEMENU_METADATA           1110
#define IDS_FILEMENU_AUTHOR             1111
#define IDS_FILEMENU_COMMENTS           1112
#define IDS_FILEMENU_KEYWORDS           1113
#define IDS_FILEMENU_TITLE              1114
#define IDS_FILEFILTER_AIR              1200
#define IDS_FILEFILTER_AIRX             1201
#define IDS_FILEFILTER_BMP              1202
#define IDS_FILEFILTER_CSV              1203
#define IDS_FILEFILTER_ICS              1204
#define IDS_FILEFILTER_JPEG             1205
#define IDS_FILEFILTER_KML              1206
#define IDS_FILEFILTER_PNG              1207
#define IDS_FILEFILTER_TIFF             1208
#define IDS_FILEFILTER_TXT              1209
#define IDS_COLUMN0                     1300
#define IDS_COLUMN1                     1301
#define IDS_COLUMN2                     1302
#define IDS_COLUMN3                     1303
#define IDS_COLUMN4                     1304
#define IDS_COLUMN5                     1305
#define IDS_COLUMN6                     1306
#define IDS_COLUMN7                     1307
#define IDS_COLUMN8                     1308
#define IDS_COLUMN9                     1309
#define IDS_COLUMN10                    1310
#define IDS_COLUMN11                    1311
#define IDS_COLUMN12                    1312
#define IDS_COLUMN13                    1313
#define IDS_COLUMN14                    1314
#define IDS_COLUMN15                    1315
#define IDS_COLUMN16                    1316
#define IDS_COLUMN17                    1317
#define IDS_COLUMN18                    1318
#define IDS_COLUMN19                    1319
#define IDS_COLUMN20                    1320
#define IDS_COLUMN21                    1321
#define IDS_COLUMN22                    1322
#define IDS_COLUMN23                    1323
#define IDS_COLUMN24                    1324
#define IDD_CHOOSEDETAILS               2000
#define IDC_VIEWATTRIBUTES              2001
#define IDC_CHECKALL                    2002
#define IDC_UNCHECKALL                  2003
#define IDC_MOVEUP                      2004
#define IDC_MOVEDOWN                    2005
#define IDD_GLOBEOPTIONS                2100
#define IDC_MODELQUALITY                2101
#define IDC_TEXTUREQUALITY              2102
#define IDC_TEXTURECOMPRESS             2103
#define IDC_SPOTS                       2104
#define IDC_AIRPORTIATA                 2105
#define IDC_AIRPORTNAMES                2106
#define IDC_GPSCOORDINATES              2107
#define IDC_MOVEMENTS                   2108
#define IDC_DARKBACKGROUND              2109
#define IDD_ABOUT                       2200
#define IDC_NAUTICALMILES               2201
#define IDC_STATUTEMILES                2202
#define IDC_REGNAME                     2204
#define IDC_PURCHASEDATE                2205
#define IDC_PURCHASEID                  2206
#define IDC_PRODUCT                     2207
#define IDC_QUANTITYTITLE               2208
#define IDC_QUANTITY                    2209
#define IDC_ENABLEAUTOUPDATE            2210
#define IDC_CHECKDAILY                  2211
#define IDC_CHECKWEEKLY                 2212
#define IDC_CHECKMONTHLY                2213
#define IDC_UPDATENOW                   2214
#define IDD_PROPERTIES                  2300
#define IDC_TITLE                       2301
#define IDC_AUTHOR                      2302
#define IDC_KEYWORDS                    2303
#define IDC_COMMENTS                    2304
#define IDD_STATISTICS                  2400
#define IDC_FILTER_AIRPORT              2401
#define IDC_FILTER_CARRIER              2402
#define IDC_FILTER_EQUIPMENT            2403
#define IDC_FILTER_BUSINESSTRIP         2404
#define IDC_FILTER_LEISURETRIP          2405
#define IDC_FILTER_RATING               2406
#define IDC_FLIGHTCOUNT                 2407
#define IDC_TOTALDISTANCE               2408
#define IDC_TOTALFLIGHTTIME             2409
#define IDC_LONGESTFLIGHT               2410
#define IDC_SHORTESTFLIGHT              2411
#define IDC_TOTALMONEYSPENT             2412
#define IDC_TOTALMILESEARNED            2413
#define IDC_TOTALMILESSPENT             2414
#define IDC_LIST_CLASS                  2415
#define IDC_LIST_ROUTE                  2416
#define IDC_LIST_AIRPORT                2417
#define IDC_LIST_CARRIER                2418
#define IDC_LIST_EQUIPMENT              2419
#define IDD_FILTER                      2500
#define IDC_FILTER_MONTH                2501
#define IDC_FILTER_YEAR                 2502
#define IDC_SORTDIRECTION               2503
#define IDD_EDITFLIGHT_ROUTE            2600
#define IDC_FROM_IATA                   2601
#define IDC_FROM_SELECT                 2602
#define IDC_FROM_NAME                   2603
#define IDC_FROM_TIME                   2604
#define IDC_FROM_GATE                   2605
#define IDC_TO_IATA                     2606
#define IDC_TO_SELECT                   2607
#define IDC_TO_NAME                     2608
#define IDC_TO_TIME                     2609
#define IDC_TO_GATE                     2610
#define IDC_WAYPOINT_BTN                2611
#define IDC_WAYPOINT_DISPLAY            2612
#define IDC_FLIGHTTIME                  2613
#define IDC_GROUNDTRANSPORTATION        2614
#define IDC_COMMENT                     2615
#define IDD_EDITFLIGHT_OTHER            2700
#define IDC_CARRIER                     2701
#define IDC_FLIGHTNO                    2702
#define IDC_CODESHARES                  2703
#define IDC_EQUIPMENT                   2704
#define IDC_REGISTRATION                2705
#define IDC_AIRCRAFTNAME                2706
#define IDC_CLASS_Y                     2707
#define IDC_CLASS_YP                    2708
#define IDC_CLASS_J                     2709
#define IDC_CLASS_F                     2710
#define IDC_CLASS_C                     2711
#define IDC_CLASS_H                     2712
#define IDC_ETIXCODE                    2713
#define IDC_FARE                        2714
#define IDC_BUSINESSTRIP                2715
#define IDC_LEISURETRIP                 2716
#define IDC_CANCELLED                   2717
#define IDC_AWARDMILES                  2718
#define IDC_STATUSMILES                 2719
#define IDC_UPGRADEVOUCHER              2720
#define IDC_AWARDFLIGHT                 2721
#define IDC_UPGRADE                     2722
#define IDC_COLORINDICATOR              2723
#define IDC_CHOOSECOLOR                 2724
#define IDC_RATING                      2725
#define IDC_SEAT                        2726
#define IDD_EDITFLIGHT_ATTACHMENTS      2800
#define IDC_FILEVIEW                    2801
#define IDD_ADDROUTE                    2900
#define IDC_ROUTE                       2901
#define IDD_ATTACHMENTS                 3000
#define IDD_FIND                        3100
#define IDD_REPLACE                     3200
#define IDC_SEARCHTERM                  3201
#define IDC_REPLACECAPTION              3202
#define IDC_REPLACETERM                 3203
#define IDC_MATCHCASE                   3204
#define IDC_MATCHENTIRECELL             3205
#define IDC_MATCHCOLUMNONLY             3206
#define IDC_REPLACEALL                  3207
#define IDD_MAPSETTINGS_RESOLUTION      3300
#define IDC_RESOLUTIONPRESETS           3301
#define IDC_USERDEFINEDRESOLUTION       3302
#define IDC_WIDTH                       3303
#define IDC_HEIGHT                      3304
#define IDD_MAPSETTINGS_BACKGROUND      3400
#define IDC_BACKGROUND                  3401
#define IDC_BACKGROUNDCOLOR_INDICATOR   3402
#define IDC_BACKGROUNDCOLOR_CHOOSE      3403
#define IDC_BACKGROUND_PREVIEW          3404
#define IDC_BACKGROUNDCENTER_ATLANTIC   3405
#define IDC_BACKGROUNDCENTER_PACIFIC    3406
#define IDC_WIDEBORDER                  3407
#define IDC_SCALE_ALLOWSMALLER          3408
#define IDC_SCALE_ALWAYSDEFAULT         3409
#define IDC_SCALE_ALWAYSDOUBLE          3410
#define IDD_MAPSETTINGS_LOCATIONS       3500
#define IDC_METROPOLITAN_MERGE          3501
#define IDC_METROPOLITAN_PREVIEW        3502
#define IDC_SHOWLOCATIONS               3503
#define IDC_LOCATIONS_INNER_INDICATOR   3504
#define IDC_LOCATIONS_INNER_CHOOSE      3505
#define IDC_LOCATIONS_OUTER_INDICATOR   3506
#define IDC_LOCATIONS_OUTER_CHOOSE      3507
#define IDC_SHOWIATACODES               3508
#define IDC_IATACODES_INNER_INDICATOR   3509
#define IDC_IATACODES_INNER_CHOOSE      3510
#define IDC_IATACODES_OUTER_INDICATOR   3511
#define IDC_IATACODES_OUTER_CHOOSE      3512
#define IDD_MAPSETTINGS_ROUTES          3600
#define IDC_SHOWROUTES                  3601
#define IDC_ROUTECOLOR_INDICATOR        3602
#define IDC_ROUTECOLOR_CHOOSE           3603
#define IDC_USECOLORS                   3604
#define IDC_STRAIGHTLINES               3605
#define IDC_ARROWS                      3606
#define IDC_USECOUNT_WIDTH              3607
#define IDC_USECOUNT_OPACITY            3608
#define IDC_NOTES_SMALLFONT             3609
#define IDC_NOTECOLOR_INNER_INDICATOR   3610
#define IDC_NOTECOLOR_INNER_CHOOSE      3611
#define IDC_NOTECOLOR_OUTER_INDICATOR   3612
#define IDC_NOTECOLOR_OUTER_CHOOSE      3613
#define IDC_STRAIGHTLINES6              3613
#define IDC_NOTES_DISTANCE              3614
#define IDC_NOTES_FLIGHTTIME            3615
#define IDC_NOTES_FLIGHTCOUNT           3616
#define IDC_NOTES_CARRIER               3617
#define IDC_NOTES_EQUIPMENT             3618
#define IDD_GLOBESETTINGS               3700
#define IDD_GOOGLEEARTHSETTINGS         3800
#define IDC_CLAMPHEIGHT                 3801
#define IDD_STATISTICSSETTINGS          3900
#define IDC_MERGEDIRECTIONS             3901
#define IDC_MERGEAWARDS                 3902
#define IDC_MERGECLASSES                3903
#define IDM_SIDEBAR_FILEMENU            4000
#define IDM_SIDEBAR_MAP_OPEN            4001
#define IDM_SIDEBAR_MAP_SETTINGS        4002
#define IDM_SIDEBAR_GLOBE_OPEN          4003
#define IDM_SIDEBAR_GLOBE_SETTINGS      4004
#define IDM_SIDEBAR_GOOGLEEARTH_OPEN    4005
#define IDM_SIDEBAR_GOOGLEEARTH_SETTINGS 4006
#define IDM_SIDEBAR_STATISTICS_OPEN     4007
#define IDM_SIDEBAR_STATISTICS_SETTINGS 4008
#define IDM_FILE_VIEWINFOLDER           4100
#define IDM_FILE_NEW                    4101
#define IDM_FILE_NEWSAMPLE1             4102
#define IDM_FILE_NEWSAMPLE2             4103
#define IDM_FILE_OPEN                   4104
#define IDM_FILE_OPENRECENT             4105
#define IDM_FILE_CLOSE                  4106
#define IDM_FILE_SAVE                   4107
#define IDM_FILE_SAVEAS                 4108
#define IDM_FILE_SAVEAS_CSV             4109
#define IDM_FILE_SAVEAS_TXT             4110
#define IDM_FILE_SAVEAS_OTHER           4111
#define IDM_FILE_PRINT                  4112
#define IDM_FILE_PRINTQUICK             4113
#define IDM_FILE_PROPERTIES             4114
#define IDM_FILE_ATTACHMENTS            4115
#define IDM_FILE_RECENTPANE             4150
#define IDM_FILE_RECENTPANE_OPEN        4151
#define IDM_FILE_RECENTPANE_REMOVE      4152
#define IDM_MAPWND                      4200
#define IDM_MAPWND_ZOOMIN               4201
#define IDM_MAPWND_ZOOMOUT              4202
#define IDM_MAPWND_SAVEAS               4203
#define IDM_MAPWND_PRINT                4204
#define IDM_MAPWND_COPY                 4205
#define IDM_GLOBEWND                    4300
#define IDM_GLOBEWND_JUMPTOLOCATION     4301
#define IDM_GLOBEWND_ZOOMIN             4302
#define IDM_GLOBEWND_ZOOMOUT            4303
#define IDM_GLOBEWND_AUTOSIZE           4304
#define IDM_GLOBEWND_SAVEAS             4305
#define IDM_GLOBEWND_GOOGLEEARTH        4306
#define IDM_GLOBEWND_LIQUIDFOLDERS      4307
#define IDM_GLOBEWND_SETTINGS           4308
#define IDM_GLOBEWND_ITEM               4350
#define IDM_DETAILS                     4400
#define IDM_DETAILS_AUTOSIZEALL         4401
#define IDM_DETAILS_AUTOSIZE            4402
#define IDM_DETAILS_CHOOSE              4403
#define IDM_DATAGRID                    4500
#define IDM_DATAGRID_CUT                4501
#define IDM_DATAGRID_COPY               4502
#define IDM_DATAGRID_PASTE              4503
#define IDM_DATAGRID_DELETE             4504
#define IDM_DATAGRID_EDITFLIGHT         4505
#define IDM_DATAGRID_ADDROUTE           4506
#define IDM_DATAGRID_FIND               4507
#define IDM_DATAGRID_REPLACE            4508
#define IDM_DATAGRID_FINDREPLACE        4509
#define IDM_DATAGRID_FINDREPLACEAGAIN   4510
#define IDM_DATAGRID_FILTER             4511
#define IDM_DATAGRID_INSERTROW          4512
#define IDM_DATAGRID_SELECTALL          4513
#define IDM_FILEVIEW_ADD                4600
#define IDM_FILEVIEW_OPEN               4601
#define IDM_FILEVIEW_SAVEAS             4602
#define IDM_FILEVIEW_DELETE             4603
#define IDM_FILEVIEW_RENAME             4604
#define IDM_FILEVIEW_ITEM               4650
#define IDM_FILEVIEW_BACKGROUND         4651
#define IDA_ACCELERATOR_MAIN            5000
#define IDA_ACCELERATOR_MAP             5001
#define IDA_ACCELERATOR_GLOBE           5002

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        8013
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         8056
#define _APS_NEXT_SYMED_VALUE           8007
#endif
#endif
