//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Flightmap.rc
//
#define IDB_RESOLUTIONPRESETICONS_16    130
#define IDB_RESOLUTIONPRESETICONS_24    131
#define IDB_RESOLUTIONPRESETICONS_32    132
#define IDB_SIDEBAR_16                  133
#define IDB_SIDEBAR_24                  134
#define IDB_SIDEBAR_32                  135
#define IDB_SIDEBAR_48                  136
#define IDB_SIDEBAR_64                  137
#define IDB_TASKS_ATTACHMENTS_16        138
#define IDB_TASKS_ATTACHMENTS_24        139
#define IDB_TASKS_ATTACHMENTS_32        140
#define IDB_TASKS_ATTACHMENTS_48        141
#define IDB_TASKS_ATTACHMENTS_64        142
#define IDB_TASKS_ITINERARY_16          143
#define IDB_TASKS_ITINERARY_24          144
#define IDB_TASKS_ITINERARY_32          145
#define IDB_TASKS_ITINERARY_48          146
#define IDB_TASKS_ITINERARY_64          147
#define IDB_TASKS_MAP_16                148
#define IDB_TASKS_MAP_24                149
#define IDB_TASKS_MAP_32                150
#define IDB_TASKS_MAP_48                151
#define IDB_TASKS_MAP_64                152
#define IDB_TASKS_GLOBE_16              153
#define IDB_TASKS_GLOBE_24              154
#define IDB_TASKS_GLOBE_32              155
#define IDB_TASKS_GLOBE_48              156
#define IDB_TASKS_GLOBE_64              157
#define IDB_FLAGS_16                    158
#define IDB_FLAGS_24                    159
#define IDB_FLAGS_32                    160
#define IDB_FLAGS_48                    161
#define IDB_FLAGS_64                    162
#define IDB_FLAGS_16i                   163
#define IDB_FLAGS_24i                   164
#define IDB_FLAGS_32i                   165
#define IDB_METROPOLITAN_DISTINCT       166
#define IDB_METROPOLITAN_MERGED         167
#define IDB_SEATICONS                   168
#define IDB_BLUEMARBLE_512              169
#define IDB_NIGHT_512                   170
#define IDB_NIGHT_8192                  171
#define IDB_ABSTRACT_512                172
#define IDB_ABSTRACT_8192               173
#define IDS_DRIVENOTREADY               1000
#define IDS_ILLEGALFORMAT               1001
#define IDS_FLIGHTCOUNT_SINGULAR        1002
#define IDS_FLIGHTCOUNT_PLURAL          1003
#define IDS_BACKGROUND_DEFAULT          1004
#define IDS_BACKGROUND_NIGHT            1005
#define IDS_BACKGROUND_ABSTRACT         1006
#define IDS_BACKGROUND_COLOR            1007
#define IDS_EMPTYITINERARY              1008
#define IDS_FILTEREDITINERARY           1009
#define IDS_SAMPLEITINERARY             1010
#define IDS_NOTSAVED                    1011
#define IDS_ATTACHMENTS                 1012
#define IDS_AWARDFLIGHT                 1013
#define IDS_GROUNDTRANSPORTATION        1014
#define IDS_BUSINESSTRIP                1015
#define IDS_LEISURETRIP                 1016
#define IDS_UPGRADE                     1017
#define IDS_CANCELLED                   1018
#define IDS_EDITFLIGHT                  1019
#define IDS_CUEBANNER_DATETIME          1020
#define IDS_CUEBANNER_TIME              1021
#define IDS_CUEBANNER_ROUTE             1022
#define IDS_PRINTED_UNREGISTERED        1023
#define IDS_PRINTED_REGISTERED          1024
#define IDS_METADATA_COMMENTS           1025
#define IDS_METADATA_TITLE_ATLANTIC     1026
#define IDS_METADATA_TITLE_PACIFIC      1027
#define IDS_METADATA_KEYWORDS_ATLANTIC  1028
#define IDS_METADATA_KEYWORDS_PACIFIC   1029
#define IDS_SUBITEM_NAME                1030
#define IDS_SUBITEM_CREATED             1031
#define IDS_SUBITEM_MODIFIED            1032
#define IDS_SUBITEM_SIZE                1033
#define IDS_ATTACHMENT_TOOLARGE         1034
#define IDS_ATTACHMENT_TOOMANY          1035
#define IDS_FILESTATUS_SINGULAR         1036
#define IDS_FILESTATUS_PLURAL           1037
#define IDS_INSPECT_METADATA_NONE       1038
#define IDS_INSPECT_METADATA_PRESENT    1039
#define IDS_INSPECT_ATTACHMENTS_NONE    1040
#define IDS_INSPECT_ATTACHMENTS_SINGULAR 1041
#define IDS_INSPECT_ATTACHMENTS_PLURAL  1042
#define IDS_DELETE_CAPTION              1043
#define IDS_DELETE_FILE                 1044
#define IDS_DELETE_ALL                  1045
#define IDS_REVENUEFLIGHTS              1046
#define IDS_NONREVFLIGHTS               1047
#define IDS_INCLUDESCREW                1048
#define IDS_CLASS_F                     1049
#define IDS_CLASS_J                     1050
#define IDS_CLASS_YP                    1051
#define IDS_CLASS_Y                     1052
#define IDS_CLASS_CHARTER               1053
#define IDS_CLASS_CREW                  1054
#define IDS_MILES                       1055
#define IDS_FLIGHTS                     1056
#define IDS_ROUTE                       1057
#define IDS_FLIGHTS_SINGULAR            1058
#define IDS_FLIGHTS_PLURAL              1059
#define IDS_RESOLUTION                  1060
#define IDS_TOOLTIP_UINT                1061
#define IDS_TOOLTIP_TIME                1062
#define IDS_TOOLTIP_DISTANCE            1063
#define IDS_TOOLTIP_DATETIME            1064
#define IDS_FINDREPLACE                 1065
#define IDS_ILLEGALCOLUMN_FIND          1066
#define IDS_ILLEGALCOLUMN_REPLACE       1067
#define IDS_ALLREPLACED                 1068
#define IDS_SEARCHTERMNOTFOUND          1069
#define IDS_REPLACEQUESTION             1070
#define IDS_NORENDERINGCONTEXT          1071
#define IDS_QUALITY_LOW                 1072
#define IDS_QUALITY_MEDIUM              1073
#define IDS_QUALITY_HIGH                1074
#define IDS_QUALITY_ULTRA               1075
#define IDS_GOOGLEEARTH                 1076
#define IDS_STATISTICS                  1077
#define IDS_MAPSETTINGS                 1078
#define IDS_COLUMN_RESOLUTION           1079
#define IDS_COLUMN_APPLICATION          1080
#define IDS_FILEFILTER_AIR              1100
#define IDS_FILEFILTER_AIRX             1101
#define IDS_FILEFILTER_BMP              1102
#define IDS_FILEFILTER_CSV              1103
#define IDS_FILEFILTER_ICS              1104
#define IDS_FILEFILTER_JPEG             1105
#define IDS_FILEFILTER_KML              1106
#define IDS_FILEFILTER_PNG              1107
#define IDS_FILEFILTER_TIFF             1108
#define IDS_FILEFILTER_TXT              1109
#define IDS_COLUMN0                     1200
#define IDS_COLUMN1                     1201
#define IDS_COLUMN2                     1202
#define IDS_COLUMN3                     1203
#define IDS_COLUMN4                     1204
#define IDS_COLUMN5                     1205
#define IDS_COLUMN6                     1206
#define IDS_COLUMN7                     1207
#define IDS_COLUMN8                     1208
#define IDS_COLUMN9                     1209
#define IDS_COLUMN10                    1210
#define IDS_COLUMN11                    1211
#define IDS_COLUMN12                    1212
#define IDS_COLUMN13                    1213
#define IDS_COLUMN14                    1214
#define IDS_COLUMN15                    1215
#define IDS_COLUMN16                    1216
#define IDS_COLUMN17                    1217
#define IDS_COLUMN18                    1218
#define IDS_COLUMN19                    1219
#define IDS_COLUMN20                    1220
#define IDS_COLUMN21                    1221
#define IDS_COLUMN22                    1222
#define IDS_COLUMN23                    1223
#define IDS_COLUMN24                    1224
#define IDD_CHOOSEDETAILS               2000
#define IDC_VIEWATTRIBUTES              2001
#define IDC_CHECKALL                    2002
#define IDC_UNCHECKALL                  2003
#define IDC_MOVEUP                      2004
#define IDC_MOVEDOWN                    2005
#define IDD_GLOBEOPTIONS                2100
#define IDC_MODELQUALITY                2101
#define IDC_TEXTUREQUALITY              2102
#define IDC_TEXTURECOMPRESS             2103
#define IDC_SPOTS                       2104
#define IDC_AIRPORTIATA                 2105
#define IDC_AIRPORTNAMES                2106
#define IDC_GPSCOORDINATES              2107
#define IDC_MOVEMENTS                   2108
#define IDC_DARKBACKGROUND              2109
#define IDD_ABOUT                       2200
#define IDC_NAUTICALMILES               2201
#define IDC_STATUTEMILES                2202
#define IDC_REGNAME                     2204
#define IDC_PURCHASEDATE                2205
#define IDC_PURCHASEID                  2206
#define IDC_PRODUCT                     2207
#define IDC_QUANTITYTITLE               2208
#define IDC_QUANTITY                    2209
#define IDC_ENABLEAUTOUPDATE            2210
#define IDC_CHECKDAILY                  2211
#define IDC_CHECKWEEKLY                 2212
#define IDC_CHECKMONTHLY                2213
#define IDC_UPDATENOW                   2214
#define IDD_PROPERTIES                  2300
#define IDC_TITLE                       2301
#define IDC_AUTHOR                      2302
#define IDC_KEYWORDS                    2303
#define IDC_COMMENTS                    2304
#define IDD_INSPECT                     2400
#define IDC_METADATA_STATUS             2401
#define IDC_METADATA_SHOW               2402
#define IDC_METADATA_DELETE             2403
#define IDC_ATTACHMENTS_STATUS          2404
#define IDC_ATTACHMENTS_SHOW            2405
#define IDC_ATTACHMENTS_DELETE          2406
#define IDD_STATISTICS                  2500
#define IDC_FILTER_AIRPORT              2501
#define IDC_FILTER_CARRIER              2502
#define IDC_FILTER_EQUIPMENT            2503
#define IDC_FILTER_BUSINESSTRIP         2504
#define IDC_FILTER_LEISURETRIP          2505
#define IDC_FILTER_RATING               2506
#define IDC_FLIGHTCOUNT                 2507
#define IDC_TOTALDISTANCE               2508
#define IDC_TOTALFLIGHTTIME             2509
#define IDC_LONGESTFLIGHT               2510
#define IDC_SHORTESTFLIGHT              2511
#define IDC_TOTALMONEYSPENT             2512
#define IDC_TOTALMILESEARNED            2513
#define IDC_TOTALMILESSPENT             2514
#define IDC_LIST_CLASS                  2515
#define IDC_LIST_ROUTE                  2516
#define IDC_LIST_AIRPORT                2517
#define IDC_LIST_CARRIER                2518
#define IDC_LIST_EQUIPMENT              2519
#define IDD_FILTER                      2600
#define IDC_FILTER_MONTH                2601
#define IDC_FILTER_YEAR                 2602
#define IDC_SORTDIRECTION               2603
#define IDD_EDITFLIGHT_ROUTE            2700
#define IDC_FROM_IATA                   2701
#define IDC_FROM_SELECT                 2702
#define IDC_FROM_NAME                   2703
#define IDC_FROM_TIME                   2704
#define IDC_FROM_GATE                   2705
#define IDC_TO_IATA                     2706
#define IDC_TO_SELECT                   2707
#define IDC_TO_NAME                     2708
#define IDC_TO_TIME                     2709
#define IDC_TO_GATE                     2710
#define IDC_WAYPOINT_BTN                2711
#define IDC_WAYPOINT_DISPLAY            2712
#define IDC_FLIGHTTIME                  2713
#define IDC_GROUNDTRANSPORTATION        2714
#define IDC_COMMENT                     2715
#define IDD_EDITFLIGHT_OTHER            2800
#define IDC_CARRIER                     2801
#define IDC_FLIGHTNO                    2802
#define IDC_CODESHARES                  2803
#define IDC_EQUIPMENT                   2804
#define IDC_REGISTRATION                2805
#define IDC_AIRCRAFTNAME                2806
#define IDC_CLASS_Y                     2807
#define IDC_CLASS_YP                    2808
#define IDC_CLASS_J                     2809
#define IDC_CLASS_F                     2810
#define IDC_CLASS_C                     2811
#define IDC_CLASS_H                     2812
#define IDC_ETIXCODE                    2813
#define IDC_FARE                        2814
#define IDC_BUSINESSTRIP                2815
#define IDC_LEISURETRIP                 2816
#define IDC_CANCELLED                   2817
#define IDC_AWARDMILES                  2818
#define IDC_STATUSMILES                 2819
#define IDC_UPGRADEVOUCHER              2820
#define IDC_AWARDFLIGHT                 2821
#define IDC_UPGRADE                     2822
#define IDC_COLORINDICATOR              2823
#define IDC_CHOOSECOLOR                 2824
#define IDC_RATING                      2825
#define IDC_SEAT                        2826
#define IDD_EDITFLIGHT_ATTACHMENTS      2900
#define IDC_FILEVIEW                    2901
#define IDC_FILESTATUS                  2902
#define IDD_ADDROUTE                    3000
#define IDC_ROUTE                       3001
#define IDD_ATTACHMENTS                 3100
#define IDD_FIND                        3200
#define IDD_REPLACE                     3300
#define IDC_SEARCHTERM                  3301
#define IDC_REPLACECAPTION              3302
#define IDC_REPLACETERM                 3303
#define IDC_MATCHCASE                   3304
#define IDC_MATCHENTIRECELL             3305
#define IDC_MATCHCOLUMNONLY             3306
#define IDC_REPLACEALL                  3307
#define IDD_MAPSETTINGS_RESOLUTION      3400
#define IDC_RESOLUTIONPRESETS           3401
#define IDC_USERDEFINEDRESOLUTION       3402
#define IDC_WIDTH                       3403
#define IDC_HEIGHT                      3404
#define IDD_MAPSETTINGS_BACKGROUND      3500
#define IDC_BACKGROUND                  3501
#define IDC_BACKGROUNDCOLOR_INDICATOR   3502
#define IDC_BACKGROUNDCOLOR_CHOOSE      3503
#define IDC_BACKGROUND_PREVIEW          3504
#define IDC_BACKGROUNDCENTER_ATLANTIC   3505
#define IDC_BACKGROUNDCENTER_PACIFIC    3506
#define IDC_WIDEBORDER                  3507
#define IDD_MAPSETTINGS_LOCATIONS       3600
#define IDC_METROPOLITAN_MERGE          3601
#define IDC_METROPOLITAN_PREVIEW        3602
#define IDC_SHOWLOCATIONS               3603
#define IDC_LOCATIONS_INNER_INDICATOR   3604
#define IDC_LOCATIONS_INNER_CHOOSE      3605
#define IDC_LOCATIONS_OUTER_INDICATOR   3606
#define IDC_LOCATIONS_OUTER_CHOOSE      3607
#define IDC_SHOWIATACODES               3608
#define IDC_IATACODES_INNER_INDICATOR   3609
#define IDC_IATACODES_INNER_CHOOSE      3610
#define IDC_IATACODES_OUTER_INDICATOR   3611
#define IDC_IATACODES_OUTER_CHOOSE      3612
#define IDD_MAPSETTINGS_ROUTES          3700
#define IDC_SHOWROUTES                  3701
#define IDC_ROUTECOLOR_INDICATOR        3702
#define IDC_ROUTECOLOR_CHOOSE           3703
#define IDC_USECOLORS                   3704
#define IDC_STRAIGHTLINES               3705
#define IDC_ARROWS                      3706
#define IDC_USECOUNT_WIDTH              3707
#define IDC_USECOUNT_OPACITY            3708
#define IDC_NOTES_SMALLFONT             3709
#define IDC_NOTECOLOR_INNER_INDICATOR   3710
#define IDC_NOTECOLOR_INNER_CHOOSE      3711
#define IDC_NOTECOLOR_OUTER_INDICATOR   3712
#define IDC_NOTECOLOR_OUTER_CHOOSE      3713
#define IDC_STRAIGHTLINES6              3713
#define IDC_NOTES_DISTANCE              3714
#define IDC_NOTES_FLIGHTTIME            3715
#define IDC_NOTES_FLIGHTCOUNT           3716
#define IDC_NOTES_CARRIER               3717
#define IDC_NOTES_EQUIPMENT             3718
#define IDD_GLOBESETTINGS               3800
#define IDD_GOOGLEEARTHSETTINGS         3900
#define IDC_CLAMPHEIGHT                 3901
#define IDD_STATISTICSSETTINGS          4000
#define IDC_MERGEDIRECTIONS             4001
#define IDC_MERGEAWARDS                 4002
#define IDC_MERGECLASSES                4003
#define IDM_SIDEBAR_ITINERARY           5000
#define IDM_SIDEBAR_MAP_OPEN            5001
#define IDM_SIDEBAR_MAP_SETTINGS        5002
#define IDM_SIDEBAR_GLOBE_OPEN          5003
#define IDM_SIDEBAR_GLOBE_SETTINGS      5004
#define IDM_SIDEBAR_GOOGLEEARTH_OPEN    5005
#define IDM_SIDEBAR_GOOGLEEARTH_SETTINGS 5006
#define IDM_SIDEBAR_STATISTICS_OPEN     5007
#define IDM_SIDEBAR_STATISTICS_SETTINGS 5008
#define IDM_MAPWND                      5200
#define IDM_MAPWND_ZOOMIN               5201
#define IDM_MAPWND_ZOOMOUT              5202
#define IDM_MAPWND_SAVEAS               5203
#define IDM_MAPWND_PRINT                5204
#define IDM_MAPWND_COPY                 5205
#define IDM_GLOBEWND                    5300
#define IDM_GLOBEWND_JUMPTOLOCATION     5301
#define IDM_GLOBEWND_ZOOMIN             5302
#define IDM_GLOBEWND_ZOOMOUT            5303
#define IDM_GLOBEWND_AUTOSIZE           5304
#define IDM_GLOBEWND_SAVEAS             5305
#define IDM_GLOBEWND_GOOGLEEARTH        5306
#define IDM_GLOBEWND_LIQUIDFOLDERS      5307
#define IDM_GLOBEWND_SETTINGS           5308
#define IDM_GLOBEWND_ITEM               5350
#define IDM_DETAILS                     5400
#define IDM_DETAILS_AUTOSIZEALL         5401
#define IDM_DETAILS_AUTOSIZE            5402
#define IDM_DETAILS_CHOOSE              5403
#define IDM_DATAGRID                    5500
#define IDM_DATAGRID_CUT                5501
#define IDM_DATAGRID_COPY               5502
#define IDM_DATAGRID_PASTE              5503
#define IDM_DATAGRID_DELETE             5504
#define IDM_DATAGRID_EDITFLIGHT         5505
#define IDM_DATAGRID_ADDROUTE           5506
#define IDM_DATAGRID_FIND               5507
#define IDM_DATAGRID_REPLACE            5508
#define IDM_DATAGRID_FINDREPLACE        5509
#define IDM_DATAGRID_FINDREPLACEAGAIN   5510
#define IDM_DATAGRID_FILTER             5511
#define IDM_DATAGRID_INSERTROW          5512
#define IDM_DATAGRID_SELECTALL          5513
#define IDM_FILEVIEW_ADD                5600
#define IDM_FILEVIEW_OPEN               5601
#define IDM_FILEVIEW_SAVEAS             5602
#define IDM_FILEVIEW_DELETE             5603
#define IDM_FILEVIEW_RENAME             5604
#define IDM_FILEVIEW_ITEM               5650
#define IDM_FILEVIEW_BACKGROUND         5651
#define IDM_FILE                        5700
#define IDM_FILE_NEW                    5701
#define IDM_FILE_NEWSAMPLE1             5702
#define IDM_FILE_NEWSAMPLE2             5703
#define IDM_FILE_OPEN                   5704
#define IDM_FILE_SAVE                   5705
#define IDM_FILE_SAVEAS                 5706
#define IDM_FILE_SAVEAS_AIRX            5707
#define IDM_FILE_SAVEAS_ICS             5708
#define IDM_FILE_SAVEAS_CSV             5709
#define IDM_FILE_SAVEAS_TXT             5710
#define IDM_FILE_SAVEAS_OTHER           5711
#define IDM_FILE_PRINT                  5712
#define IDM_FILE_PRINT_QUICK            5713
#define IDM_FILE_PREPARE                5714
#define IDM_FILE_PREPARE_PROPERTIES     5715
#define IDM_FILE_PREPARE_INSPECT        5716
#define IDM_FILE_PREPARE_ATTACHMENTS    5717
#define IDM_FILE_CLOSE                  5718
#define IDM_FILE_RECENT                 5750
#define IDA_ACCELERATOR_MAIN            6000
#define IDA_ACCELERATOR_MAP             6001
#define IDA_ACCELERATOR_GLOBE           6002
#define IDC_CHECK1                      8054

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        8013
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         8055
#define _APS_NEXT_SYMED_VALUE           8007
#endif
#endif
